### ISSUE TITLE
Express: Make Tests for Input

### ISSUE THREAD

**Issue by gagataiga** [gagataiga/Phone-Review-App#8]
Write some tests to check that the input values are legitimate before adding them to the database (i.e., check that the Email input is actually an email address instead of random letters).

All of the fields should be filled in before submission (no leaving Nickname empty, for example).

**Comment by kappanjoe** [comment]
From previous team's comments:

// Nickname !== ""
// email -
1.) list of characters allowed, excluding special characters,
2.) required .com,
3.) make @ dividing the email name and domain
4.) email domain should not have special character (any special character before .com should not be allowed).
5.) lowercase for all characters. -should auto change it to lowercase or warn user to input lowercase email
// dropdown menu - alert user when user did not select any company brand, ie. companyName !== ""

Hints for email, check codewars similar exercise:
https://www.codewars.com/kata/514a024011ea4fb54200004b

// Self suggestion
// Add an alert window to confirm user choice / alert user with error on screen

Add checks within the /api/review post endpoint.
These test should
-check that the email is in an email format (could also use type='email' in the input component).
-check the score numbers are valid
-profanity filter for reviews/names

if review is invalid, return falsey statement
